language: node_js
node_js:
    - "stable"
    - "4"
    - "0.12"
jobs:
  include:
    # With Node.js 5, we need a version of npm higher than the default from NVM
    # Otherwise we hit https://github.com/npm/cli/issues/681
    - name: "Node.js 5"
      node_js: "5"
      before_install:
        - npm i -g npm@4.6.1

    - name: "Check codestyle"
      script: npm run check-codestyle
