on:
  pull_request: {}
  push:
    branches:
      - main

name: Continuous Integration

env:
  default_node_version: 22

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test supported release Node.js versions (even numbers) plus current
        # development version.
        node_version: [14, 16, 18, 20, 22, 24]

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: npm install

      - name: Run loader tests
        run: |
          npm test

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: npm install

      - name: Check Integration
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          DATADOG_SITE: ${{ secrets.DATADOG_API_HOST }}
        run: |
          npm run check-integration

  test-deno-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: '~2.1'

      - name: Install dependencies
        run: deno install

      - name: Check Integration
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          DATADOG_SITE: ${{ secrets.DATADOG_API_HOST }}
        run: |
          deno --allow-all test-other/integration_check_deno.ts

  test-bun-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.0.36'

      - name: Install dependencies
        run: bun install

      - name: Check Integration
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
          DATADOG_SITE: ${{ secrets.DATADOG_API_HOST }}
        run: |
          bun test-other/integration_check.mjs '-bun'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: npm install

      - name: Lint Code
        run: |
          npm run check-codestyle

      - name: Lint Text
        run: npm run check-text

  types:
    name: Build/Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Install dependencies
        run: npm install

      - name: Build Types
        run: |
          npm run build-types

      - name: Check Types
        run: |
          npm run check-types
